### ISSUE TITLE
Icon "ri-group-2-line" not found in UI

### ISSUE THREAD

**Issue by namtrah** [FlorianWoelki/obsidian-icon-folder#93] opened 2022-07-09 17:05 UTC
**Describe the bug**
Although the icon exists in the icon pack, the UI is not finding "ri-group-2-line" icon"

![image](https://user-images.githubusercontent.com/13903735/178115733-71f075f4-8d53-4445-a283-d15ab7b26e8b.png)

From the remix Icons, Group-2-Line(Ri) should look like this:
![image](https://user-images.githubusercontent.com/13903735/178115755-cd37fc45-5e8c-435f-8886-b27c158f76b7.png)

But when using Obsidian it cannot be found in the UI to change a folder icon. I am not sure why,.

**To Reproduce**
1. install Remix icon Line pack
2. Search for "Group2Line"
3. no icon appears

**Expected behavior**
I expect the icon (which was downloaded) to be found and displayed in the UI.

**Screenshots**

**Additional context**

**Comment by FlorianWoelki** [comment] 2022-07-12 06:26
I cannot reproduce this issue with the latest version. Please check out [the newest version](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.2.6).

**Comment by FlorianWoelki** [comment] 2022-07-13 07:14
I'll inspect this problem asap. Thanks for reporting. I'll close this issue for now.

**Closed by FlorianWoelki** 2022-07-13 07:14 UTC
Labels: question
