### ISSUE TITLE
Disappearing, Non-reappearing, Icon Packs!

### ISSUE THREAD

**Issue by gossamerephermal** [FlorianWoelki/obsidian-icon-folder#118] opened 2022-09-28 10:58 UTC
**Describe the bug**

It's magic! Every time I close Obsidian and load it again, all my icon packs disappear. This does not matter if it's one I placed in myself, or if it's one of the premade ones like Icon Brew. Upon further testing, I didn't need to close Obsidian completely, just the vault, and opening the vault again will make the packs disappear.

The pack will disappear from both "Icon Folder Settings" and no icons will display in the "Change Icon" pop up when attempting to change icons on a note or folder.

The files are still _there_ in the folder structure, they still (sometimes) display on the folders and notes I added icons to previously. Icon Folder just pretends like there's no icon packs installed and the section will be blank in the plugin settings. I've tried moving the icons around in the file structure, even outside of the .obsidian folder (ie, /attachments/icons/).

When I try to readd my custom icon pack using the same name in Icon Folder Settings, it will state the icon pack already exists. It detects the folder is there, but refuses to add it back into the list of icon packs and gives me sass. I have to delete the files and recreate the icon pack using the plugin before it will be added to the plugin again, and display any icons in "Change Icon" selection. 

I have to readd the predefined like Icon Brew too, which will just redownload and then cause errors with the IB icons existing but it won't give me sass and stop the process like it does for custom packs. 

Upon starting Obsidian there is this error in the console:

app.js:1 Obsidian Developer Console
plugin:obsidian-auto-link-title:250 loading obsidian-auto-link-title
plugin:obsidian-icon-folder:1896 loading obsidian-icon-folder
plugin:note-refactor-obsidian:6488 Loading Note Refactor plugin
plugin:obsidian-link-archive:94 Loading Link Archive plugin...
plugin:obsidian-icon-folder:260 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at eval (plugin:obsidian-icon-folder:260:27)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-icon-folder:28:58)
eval @ plugin:obsidian-icon-folder:260
fulfilled @ plugin:obsidian-icon-folder:28

All vaults display that error on load. The vaults have different plugins and one doesn't have any plugins at all but Icon Folder.

**To Reproduce**

1. Add custom icon pack
2. Add icons to notes
3. Close the vault. Open again.
4. Look at settings for Icon Folder, see nothing there in icon packs.
5. I've tested this on a new vault. It happens in every vault I've tried Icon Folder on.

**Expected behavior**
Icon packs should be loaded into the plugin on start up right? I shouldn't need to delete and readd the icon pack every time, right?

**Screenshots**
![screen1](https://user-images.githubusercontent.com/4651595/192760180-480c5076-b43b-4a0b-9ac9-9741a00379de.jpg)
custom pack listed
![screen2](https://user-images.githubusercontent.com/4651595/192760184-d76b5b6b-a579-40ae-a533-49cac2028780.jpg)
an icon is displayed
![screen3](https://user-images.githubusercontent.com/4651595/192760185-32843f90-3fc2-4820-bdd0-c29df40831fb.jpg)
close the vault (this is the other one i had opened)
![screen4](https://user-images.githubusercontent.com/4651595/192760189-4c8e531a-cb1e-464a-8198-fc2d45b3c61e.jpg)
no icon pack installed but folder is still there
![screen5](https://user-images.githubusercontent.com/4651595/192760192-b5870323-a84b-43dd-8c2f-5e1e43381e37.jpg)
no icons available to change the iconed note, yet icon still displays

**Additional context**
I've been using this plugin for a few days and this has been consistent with the two vaults I'm using it on. I tried it on a third vault and it happened there too. The vaults are in different locations. One vault has no themes or plugins other than Icon Folder.

Before you ask, 
Yes I did a search looking for fixes to see if this issue has come up before. I've looked through this git for anything that it might be.

No, I **am not** using sync. I have tried the fix anyway, moved the icons folder around several times and the issue wasn't fixed. Everything is local. I do not sync between devices. 

I am on Windows 10.

Thanks for taking the time to dev this plugin. I'm not sure why this is giving me problems.

**Comment by ShahriarKh** [comment] 2022-11-13 11:35
Perhaps it's because of file/folder names? Try naming your icon pack and its actual folder on your system without any `-` , `_` or other similar characters and see if it works.
Currently, there's a bug with icon names including those characters (#111), and I guess this gives us a clue. 🤔

**Comment by gossamerephermal** [comment] 2022-11-13 12:20
That's one of the first things I did. It doesn't matter what I name the folder, where I place it, or if it's one of the predefined ones you can download. They all disappear from the plugin upon reopening and I am unable to set icons for notes. As of this last update, I am still unable to set icons until I delete the folder off the system and readd the icon pack through the plugin.

**Comment by GinoReiji** [comment] 2023-03-14 23:28
I have the same problem, too. Every time I want to add/ change an icon to a note, I have to move all the icons out and create the pack again. They only work that one time and will disappear the next time I restart obsidian. Though if the icon pack is not there in the first place, the icon can't be displayed, so it's just that somehow they won't show up on the menu anymore and I'll have to re-add the pack to make them show again

**Comment by gossamerephermal** [comment] 2023-05-03 12:06
As of 2.0.0 this still happens. I just tested two vaults.

**Comment by kin30528** [comment] 2023-05-03 16:38
After I updated the ob yesterday, the icons setting disappeared again ....

**Comment by DRD161** [comment] 2023-05-03 21:09
Same issue here, I'll add an icon to a note then make some changes to the note and the icon disappears.

**Comment by gossamerephermal** [comment] 2023-05-04 15:31
> Same issue here, I'll add an icon to a note then make some changes to the note and the icon disappears.

Your problem sounds like a separate issue.  My notes keep their icons even if I edit them or reopen the vault. This is for the icon packs disappearing from the plugin itself on closing the vault and opening it again. They're still being displayed, the plugin just acts like it has no icon packs installed and you can't apply icons to new notes.

**Comment by DRD161** [comment] 2023-05-04 16:27
> > Same issue here, I'll add an icon to a note then make some changes to the note and the icon disappears.
> 
> Your problem sounds like a separate issue. My notes keep their icons even if I edit them or reopen the vault. This is for the icon packs disappearing from the plugin itself on closing the vault and opening it again. They're still being displayed, the plugin just acts like it has no icon packs installed and you can't apply icons to new notes.

Ahh you're right, my apologies I misread the question. I went ahead and filed another issue in case others are having the same problem. Thanks!

**Comment by FlorianWoelki** [comment] 2023-05-04 21:21
Could you provide me a minimal vault where I can reproduce this issue?

**Comment by gossamerephermal** [comment] 2023-05-05 12:39
[Testing.zip](https://github.com/FlorianWoelki/obsidian-icon-folder/files/11406266/Testing.zip)

A vault where the icon packs has already disappeared but icons still display. I placed them in /icons/ instead of the default path to show it's affecting the packs regardless of naming or location.

**Comment by kin30528** [comment] 2023-05-05 12:44
My icon pack is display, but icon has already disappeared, after I update the obsidian every time....

**Comment by FlorianWoelki** [comment] 2023-05-06 07:50
> 

Thank you for the vault. I was actually able to replicate this and I think it's because of a small moving issue when moving a lot of icons at the same time. I cannot fix this at the moment and I recommend to have the icons at the root of the `obsidian-icon-folder` plugin folder or reinstall the icons. We will need to see if this will be fixed with a possible new icon pack saving mechanism.

**Comment by gossamerephermal** [comment] 2023-05-06 10:18
> I cannot fix this at the moment and I recommend to have the icons at the root of the `obsidian-icon-folder` plugin folder or reinstall the icons. 
 

That's the issue. I have to reinstall them EVERY time I open Obsidian.

Prior to making this test vault and installing them in that folder, I had them installed in the default plugin locations obsidian-icon-folder and it made no difference, I still have to reinstall them. 

The icon pack itself disappears from the plugin immediately after closing and opening a vault. The icons do not display in the icon picker for notes. 

I don't move the packs or icons, and my witchicons pack has 12 icons at most. When I was first creating it, I added it one icon at a time. Still had to reinstall the pack on closing and opening.

This ocurrs whether or not I have them installed in obsidian-icon-folder or outside of it. 

It doesn't matter what the folders are named, where the folders are, or how many icons are in there.

It's a problem with the plugin forgetting it has icon packs installed.

**Comment by FlorianWoelki** [comment] 2023-05-06 11:32
> > I cannot fix this at the moment and I recommend to have the icons at the root of the `obsidian-icon-folder` plugin folder or reinstall the icons.
> 
> That's the issue. I have to reinstall them EVERY time I open Obsidian.
> 
> Prior to making this test vault and installing them in that folder, I had them installed in the default plugin locations obsidian-icon-folder and it made no difference, I still have to reinstall them.
> 
> The icon pack itself disappears from the plugin immediately after closing and opening a vault. The icons do not display in the icon picker for notes.
> 
> I don't move the packs or icons, and my witchicons pack has 12 icons at most. When I was first creating it, I added it one icon at a time. Still had to reinstall the pack on closing and opening.
> 
> This ocurrs whether or not I have them installed in obsidian-icon-folder or outside of it.
> 
> It doesn't matter what the folders are named, where the folders are, or how many icons are in there.
> 
> It's a problem with the plugin forgetting it has icon packs installed.

Ok thanks for the clarification. I had a look into your `data.json` file but there is nothing wrong with it. However, I think I've found the issue with your path. Could you please test to remove the beginning `/` of your icon pack's path and please tell me if that fixes the issue.

**Comment by gossamerephermal** [comment] 2023-05-06 15:57
The testing vault that has simply "icons" as the path seems to now have persistent packs with the / removed

One vault I've been using for testing has .obsidian/icons (never had a / at the beginning, ever) and it still disappeared the icon pack.

Default path is .obsidian/plugins/obsidian-icon-folder/icons on another testing vault, and that works now. It did not before.

So why does the default work with the . work, but not the .obsidian/icons?

Also I want to make it very clear: I first experienced this issue from the second I first installed IconFolder and was using the default path. It made the iconpacks disappear. I continued to experiment with folder locations and the - and _s left out. Yes I tried with a / at the beginning, and some without a / at the beginning of the path. Nothing was working.

So something changed where a partial resolve is possible.

**Comment by FlorianWoelki** [comment] 2023-05-07 07:37
> The testing vault that has simply "icons" as the path seems to now have persistent packs with the / removed
> 
> One vault I've been using for testing has .obsidian/icons (never had a / at the beginning, ever) and it still disappeared the icon pack.
> 
> Default path is .obsidian/plugins/obsidian-icon-folder/icons on another testing vault, and that works now. It did not before.
> 
> So why does the default work with the . work, but not the .obsidian/icons?
> 
> Also I want to make it very clear: I first experienced this issue from the second I first installed IconFolder and was using the default path. It made the iconpacks disappear. I continued to experiment with folder locations and the - and _s left out. Yes I tried with a / at the beginning, and some without a / at the beginning of the path. Nothing was working.
> 
> So something changed where a partial resolve is possible.

I fixed one more other thing, but that should not solve the problem. I am actually not able to reproduce this when I have to point the path at `.obsidian/icons`. This actually works fine for me.

**Comment by gossamerephermal** [comment] 2023-05-07 08:54
Well, I just checked another vault where the folder path has been attachments/icons and it is still disappearing the packs.

**Comment by FlorianWoelki** [comment] 2023-09-11 18:07
This issue has been probably resolved in the newest update.

**Closed by FlorianWoelki** 2023-09-11 18:07 UTC
