### ISSUE TITLE
How do i get only 1 folder icon instead of multiple icons and how can i uninstall this plugin

### ISSUE THREAD

**Issue by munish259272** [FlorianWoelki/obsidian-icon-folder#214] opened 2023-09-02 06:32 UTC
**Describe the bug**
When i clicked on inherit icon it put two icons , why does it keep adding more icons and i am unable to remove the extra icons as well.
Also, why does it applies folder icons to files when inherited

**To Reproduce**
Just clicked on inherit icon

**Expected behavior**
I just want to uninstall it now but i am unable to do that since nothing happens when i click uninstall. i tried disabling it and now i cannot enable it also and shows the pop-up failed to load obsidian-icon-folder.

**Screenshots**
![image](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/834673/71e3bef1-367b-4830-a48f-0f8d0cb435a1)

**Comment by munish259272** [comment] 2023-09-02 07:53
Ok i was able to unistall it and remove the icons.
But do you think this issue of multiple icons occurs only for me or it is a bug really

**Comment by SaifEl-Deen** [comment] 2023-09-03 19:13
I can confirm this bug, to reproduce:
1. Create a folder
2. Create notes inside that folder
3. Set an icon for the folder
4. Inherit this icon to the notes
5. Change the icon of the folder
6. Inherited icons of the notes aren't updated + "Inherit" option becomes available again
7. Inherit icons again, you will get double icons

**Comment by FlorianWoelki** [comment] 2023-09-09 13:32
Duplicate of #216.

Issue and further fixes will be tracked there.

**Closed by FlorianWoelki** 2023-09-09 13:31 UTC
Labels: duplicate
