### ISSUE TITLE
Beta-testing icon generation  

### ISSUE THREAD

**Issue by Mara-Li** [FlorianWoelki/obsidian-icon-folder#44] opened 2022-03-07 17:13 UTC
**Describe the bug**
Here we go again : when I want to build the app, the `yarn dev` print : `[!] Error: Could not resolve '../remixicons' from src\util.ts`

**To Reproduce**
1. `git clone []`
2. `cd [] && yarn && node scripts/generate-icons.js`
3. `yarn dev`

**Expected behavior**
A build

**Screenshots**
/

**Additional context**
/

**Comment by FlorianWoelki** [comment] 2022-03-10 09:23
Check out the latest version. I've tried to reproduce it.

**Comment by Mara-Li** [comment] 2022-03-11 22:39
Well, I tryed to update the plugin without any génération and i end up with no icon at all ![image](https://user-images.githubusercontent.com/30244939/157984109-77cf1727-4302-4efe-a0f7-e3a24a49ec64.png)

**Comment by Mara-Li** [comment] 2022-03-12 11:20
For me, the best thing to do is to embed by default (generation or downloading) the icon the plugin already had. 
Some idea : 

- Backup and restore options as saw in [Obsidian Icon's shortcode](https://github.com/aidenlx/obsidian-icon-shortcodes) when the plugin update.
- Built-in icons (Remix, Fontawesome) during generation, keep the option to add icons pack.
- Keep on built-icons pack, adding the rest as download and auto-creation of custom icon pack. For example, add a way to download all remix-icons line and directly create the custom pack.

**Comment by FlorianWoelki** [comment] 2022-03-12 12:31
> For me, the best thing to do is to embed by default (generation or downloading) the icon the plugin already had. Some idea :
> 
> * Backup and restore options as saw in [Obsidian Icon's shortcode](https://github.com/aidenlx/obsidian-icon-shortcodes) when the plugin update.
> * Built-in icons (Remix, Fontawesome) during generation, keep the option to add icons pack.
> * Keep on built-icons pack, adding the rest as download and auto-creation of custom icon pack, as saw in the last update of [Obsidian Icon's shortcode](https://github.com/aidenlx/obsidian-icon-shortcodes). For example, add a way to download all remix-icons line and directly create the custom pack.

Yeah I need to investigate that. Thanks though :)

**Comment by Mara-Li** [comment] 2022-03-12 21:58
Also, don't forget to build the update (from the merged fork of Alx)!

**Comment by Mara-Li** [comment] 2022-03-15 19:16
It works like a charge ! Pretty surprised by the speed of the downloading ! 
Also, you forgot to add Devicons !

**Comment by Mara-Li** [comment] 2022-03-15 19:40
![image](https://user-images.githubusercontent.com/30244939/158458184-5f6c3402-ae47-4db6-9548-4f918f313ea4.png)
Sometimes, I have this error. so I need to retry a lot to download the pack I want

**Comment by Mara-Li** [comment] 2022-03-15 19:54
![image](https://user-images.githubusercontent.com/30244939/158460317-c2380cb0-59ae-4f76-8267-f0843a5c9c3c.png)
For some reason, the plugin don't want to load. Here is the console.

**Comment by Mara-Li** [comment] 2022-03-15 19:57
Also, the plugin trying to charge the icons and crash if these icons doesn't exists (deleted manually).

**Comment by Mara-Li** [comment] 2022-03-15 21:59
And, to add more bug : The inherit icons doesn't work ; I have just the name of the icons.

**Comment by Mara-Li** [comment] 2022-03-15 22:20
Also, with Obsidian Sync the icons will don't be sync and the download can't work on mobile, so the plugin explode on mobile (at last on IOS)

**Comment by FlorianWoelki** [comment] 2022-03-16 08:32
Thanks for reporting all the issues! I think every issue should be fixed now. I've tested the newest one on my productive obsidian environment, and everything seems to work.

And actually, for mobile, it works as well. Just the syncing takes some time because of all the icons.

**Comment by Mara-Li** [comment] 2022-03-16 16:36
I will try the new build !

**Comment by Mara-Li** [comment] 2022-03-16 18:39
![image](https://user-images.githubusercontent.com/30244939/158663209-a7cbc8c9-2d76-45af-bf0a-738ccda0cc97.png)
Dunno what happen when download :/
Sometimes It just creates the folder, and download nothing.

**Comment by FlorianWoelki** [comment] 2022-03-16 19:02
Hm that's strange. I can not really reproduce that issue. Could you check out the network tab in the console and check if everything is successful?

**Comment by FlorianWoelki** [comment] 2022-03-16 19:09
Can you check out the latest version of the project? Maybe the folder was not created before the download.

The sync problem is really strange. Maybe there is some interference with other plugins?

**Comment by Mara-Li** [comment] 2022-03-16 19:50
It deleted some svg file in fact. Sometimes it upload the old version...
Moreover, the sync of the SVG file is very, very too much long. I think it's been a hour that my phone download the svg ? Or 30min.

**Comment by Mara-Li** [comment] 2022-03-16 20:00
Okay, after the sync, the file was deleted. Again.

**Comment by Mara-Li** [comment] 2022-03-16 22:51
Huh, i don't thinks it's a good option, unless you create a "migration" icon's pack. And for future user, it will be difficult to use.

I think It will be better to check how @aidenlx do with icon-shortcode, because i dont have any problem with the download-usage on mobile.

Aiden use a custom icons folder in .obsidian (root). Maybe use the same / a similary way ? It can be cool to prevent the same icon pack on two differents plugin.

**Comment by aidenlx** [comment] 2022-03-16 23:40
actually I use that folder under .obsidian intentionally to avoid syncing issue

**Comment by Mara-Li** [comment] 2022-03-16 23:43
So my guess was good :D

**Comment by FlorianWoelki** [comment] 2022-03-17 07:45
So the syncing problem is actually the duplication of icons?

I don't really like the global solution as a default option. O think, I'll add another setting to toggle between the global and local option.

**Comment by Mara-Li** [comment] 2022-03-17 08:21
> So the syncing problem is actually the duplication of icons?
> 
> I don't really like the global solution as a default option. O think, I'll add another setting to toggle between the global and local option.

No, the problem is that sync delete the icon during sync. Also the sync became too much long and unstable.

What do you mean by global ?

**Comment by FlorianWoelki** [comment] 2022-03-17 08:22
I mean with global, the solution with a directory in the root directory (.obsidian)?

**Comment by Mara-Li** [comment] 2022-03-17 11:05
Why you don't like this solution ?

**Comment by FlorianWoelki** [comment] 2022-03-17 11:39
Because it's operating outside the plugin directory. However, I can create a option that enables this creation or "detection".

**Comment by FlorianWoelki** [comment] 2022-03-17 13:15
@Mara-Li you can checkout the newest version for the customizable icon pack path. Hopefully, that helps.

**Comment by Mara-Li** [comment] 2022-03-17 21:06
> Because it's operating outside the plugin directory. However, I can create an option that enables this creation or "detection".

For me, the Best is to use this folder. It can help to prevent to download multiple time the same file if using icon-shortcode; and it must help with sync issue.

I dunno why the sync have problem. I need to ask @aidenlx for that. But, detect if exists and use the files can be a big improvement. 

I will try the new version tomorrow btw

**Comment by Mara-Li** [comment] 2022-03-19 11:35
On PC, seems to work without a problem.
It will be cool if its detects the font from icon-shortcode. It will prevent multi download same font.

**Comment by FlorianWoelki** [comment] 2022-03-19 11:38
> On PC, seems to work without a problem. It will be cool if its detects the font from icon-shortcode. It will prevent multi download same font.

You mean detecting existing icon packs in the given directory?

**Comment by Mara-Li** [comment] 2022-03-19 13:00
For example, yes !
I fact, I saw that `obsidian/icons` doesn't sync. So... I dunno how to avoid the sync error I had :(

**Comment by aidenlx** [comment] 2022-03-19 13:23
Yes, I’ve used folder in theme or snippets folder before and encountered the delete problem. I ended up using icons folder under .obsidian because it’s not included in sync

**Comment by FlorianWoelki** [comment] 2022-03-19 14:35
> For example, yes !
> 
> I fact, I saw that `obsidian/icons` doesn't sync. So... I dunno how to avoid the sync error I had :(
> 
> 
> 
> @aidenlx it's normal/intended that you choose that folder because it doesn't sync ? 

I've implemented that in the latest commit.

The sync problem is really weird though. I'll release this version in the next days.

**Comment by Mara-Li** [comment] 2022-03-19 14:38
!!
This time, after synchronisation, no problem happened : the files was detected and icons are in the navigation menu without problem !

**Comment by FlorianWoelki** [comment] 2022-03-19 15:01
>  !!
> This time, after synchronisation, no problem happened : the files was detected and icons are in the navigation menu without problem !

That's really wonderful! Glad that it worked.

**Comment by Mara-Li** [comment] 2022-03-19 19:42
Okay, so, now I want to add a custom folder of icons : boxicons.
But ! 
![image](https://user-images.githubusercontent.com/30244939/159136028-2d85802e-7f76-4a33-9dee-e10bafc9a309.png)
File are from the boxicons folder official repo, in SVG.

**Comment by Mara-Li** [comment] 2022-03-19 23:28
Also some suggestion, based icon shortcode :
- Add enable-disable button
- Add a "refresh custom icon" (very important, improve the usability of the plugin)
- Export to zip custom folder and everything 
- Create a custom folder based on icons used (from the datajson). A pretty cool Idea to improve the migration.

**Comment by FlorianWoelki** [comment] 2022-03-20 13:16
> Okay, so, now I want to add a custom folder of icons : boxicons. But ! ![image](https://user-images.githubusercontent.com/30244939/159136028-2d85802e-7f76-4a33-9dee-e10bafc9a309.png) File are from the boxicons folder official repo, in SVG.

Thanks for the report. Should be fixed now.

**Comment by FlorianWoelki** [comment] 2022-03-20 13:17
> Also some suggestion, based icon shortcode :
> 
> * Add enable-disable button
> * Add a "refresh custom icon" (very important, improve the usability of the plugin)
> * Export to zip custom folder and everything
> * Create a custom folder based on icons used (from the datajson). A pretty cool Idea to improve the migration.

I'll keep all of that in mind. For now, I will try to create a stable version of the current code base.

**Comment by Mara-Li** [comment] 2022-03-20 17:30
I think you must add the refresh custom button before the new release, because I think people /user will don't understand why the added icons doesn't appear.

**Comment by Mara-Li** [comment] 2022-03-20 17:32
It is normal that I have a "remix.zip" and "custom-icons.zip" that appear at the root of my obsidian vault ?

**Comment by FlorianWoelki** [comment] 2022-03-21 08:04
> Trying the new update : It is normal that I have a "remix.zip" and "custom-icons.zip" that appear at the root of my obsidian vault ?
> 
> Also, I think the way you do the "auto refresh/adding" things is awesome !
> 
> Ahhh I'm so happy I can use boxicons <3 Thank you so much !

Maybe it is from icon shortcodes? I do not generate any zip file, so it's not from me :D 

Glad you like it! I'll try my best to refine some code and then release the update :)

**Comment by Mara-Li** [comment] 2022-03-21 11:51
Well, strange for the zip.
I have a strange bug, on my computer : the icons from boxicons doesn't appear : They are marked with the name of the icons. I can change it, but each reload remove the icons and use the name. Boxicons is correctly loaded. 

I have a lot of notification about icons not installed, but the folder is loaded.

**Comment by FlorianWoelki** [comment] 2022-03-21 12:14
> Well, strange for the zip. I have a strange bug, on my computer : the icons from boxicons doesn't appear : They are marked with the name of the icons. I can change it, but each reload remove the icons and use the name. Boxicons is correctly loaded.
> 
> I have a lot of notification about icons not installed, but the folder is loaded. I think it's a "name" difference, maybe ?

Yeah it might be a name difference. I cannot really reproduce this locally.

**Comment by Mara-Li** [comment] 2022-03-21 12:21
I pretty sure that was that because I recreated the icon pack and I have no problem now!
I also updated the plugin locally. Maybe I forgot some update.

**Comment by FlorianWoelki** [comment] 2022-03-22 08:11
I will close this issue for now. The newest version is released! Thanks again for your feedback and input.

**Closed by FlorianWoelki** 2022-03-22 08:11 UTC
Labels: bug, enhancement
