### ISSUE TITLE
Abnormal icon size after upgrading Obsidian

### ISSUE THREAD

**Issue by Rainbell129** [FlorianWoelki/obsidian-icon-folder#30] opened 2022-01-04 01:29 UTC
I recently upgraded to v13.18 of Obsidian and the icons before my folder became gigantic.
I'm using the newest version of the plugin. 
Could this be fixed?

<img width="290" alt="Screen Shot 2022-01-04 at 9 29 05 AM" src="https://user-images.githubusercontent.com/58488160/147997789-bf69ee3a-0031-49da-a359-8ba352a1f698.png">

**Comment by Rainbell129** [comment] 2022-01-04 01:33
<img width="290" alt="Screen Shot 2022-01-04 at 9 32 36 AM" src="https://user-images.githubusercontent.com/58488160/147998021-16b4d486-feb9-44f9-86a6-576eaedfeb92.png">

If I adjust the icon size and font size the icons would be temporarily ok but still several icons fail to be rendered

**Comment by herculosh** [comment] 2022-01-04 06:33
My newest version of Obsidian is 0.13.14 and the folder sizes are becoming really huge for me as well.

**Comment by FlorianWoelki** [comment] 2022-01-04 08:01
I think it has to do with upgrading to the newest version. From what version did you update and did you have obsidian-icon-folder v1.0.54 installed before?

**Comment by Rainbell129** [comment] 2022-01-04 08:07
I think you're right. It's indeed due to the upgrading. I upgraded from v12.19 of Obsidian and yes, I have installed icon folder before (not sure what version as I upgraded the plugin this morning as well). A few people told me about this problem, and they have found that if you readjusted the icon pixel (or font size? I adjusted both so I'm not sure which one took effect) to the smallest then to 16 the icon size would be normal again.

**Comment by FlorianWoelki** [comment] 2022-01-04 08:10
Is there any way to downgrade to a version in Obsidian? I've tried to install from [the releases page](https://github.com/obsidianmd/obsidian-releases/releases) but I always get the newest one :D

**Comment by Rainbell129** [comment] 2022-01-04 08:14
There is. Which system do you use? You have to remove the cache files. If it's Windows you have to delete the cache files from  C:\Users\xxx\AppData\Local\obsidian. If you're using Mac the directory is ~/Library/Application Support/ instead. Then uninstall Obsidian and use the v12.19 installer.

**Comment by FlorianWoelki** [comment] 2022-01-04 08:44
Thank you that worked perfectly. However, I am not able to reproduce this issue in any way :D So I don't know how to deal with it yet.

**Comment by Rainbell129** [comment] 2022-01-05 04:30
Ah….well, at least the issue can be solved when readjusting the icon so it’s not that much of a problem. Thanks anyway.

Sent with a Spark<https://sparkmailapp.com/source?from=signature>
On Jan 4, 2022, 4:44 PM +0800, Florian Woelki ***@***.***>, wrote:

Thank you that worked perfectly. However, I am not able to reproduce this issue in any way :D So I don't know how to deal with it yet.

**Comment by FlorianWoelki** [comment] 2022-01-09 10:22
This issue should be now resolved with the newest version [1.0.55](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.0.55).

**Closed by FlorianWoelki** 2022-01-09 10:22 UTC
Labels: bug
