### ISSUE TITLE
Custom icon pack broken

### ISSUE THREAD

**Issue by icebruce** [FlorianWoelki/obsidian-icon-folder#133] opened 2022-11-30 01:06 UTC
After recent update the custom icon packs that I have added are not working as expected.
All icons are displayed in grey color

**To Reproduce**
1. Set icons folder to `.obsidian/icons` or `.obsidian/plugins/obsidian-icon-folder/icons`
2. Add custom icon pack
3. Set icon of a folder using one of the custom icons

**Expected behavior**
The icons should be displayed as is

**Screenshots**
![image](https://user-images.githubusercontent.com/66655064/204682438-6caae1ec-5548-4f89-8543-95561446c8f0.png)

**Additional context**
This has started happening since last updated of the plugin
Using the built-in packs works as expected

**Comment by GinoReiji** [comment] 2022-12-05 01:15
I'm having the same problem, custom icons are not showing properly, and I can't find the folder pack in the option and when I try to search for the custom icons, non was found. This seems to happen after the latest update (1.4.3)

The custom icons that have already been set up before now look like this (some are displayed properly, but others are not, e.g., the "History" folder is now just a silhouette)

![image](https://user-images.githubusercontent.com/103518137/205528463-2202457f-a666-4540-a84e-7df0cfcd9386.png)

**Comment by FlorianWoelki** [comment] 2022-12-05 07:17
Hey there!

Thank you for reporting this issue. Due to the new SVG renderer this can happen. Could you please send me an example for which specific SVG this is not working so that I can reproduce it for me locally?

**Comment by GinoReiji** [comment] 2022-12-05 07:30
@FlorianWoelki Thanks for responding! I've reinstalled the plugin and can search for the custom icons now but many of them still can't be displayed properly. Below is one of the sample svg that is not working

![006-accounting](https://user-images.githubusercontent.com/103518137/205578352-0a7d6efe-2333-4dcf-aa13-02f97b558c93.svg)

**Comment by WilsonXinxin** [comment] 2022-12-08 06:11
I seem to have encountered this problem. my custom svg icon color be missing. But it exists when previewing
![image](https://user-images.githubusercontent.com/43174390/206371118-7d298584-fa4c-460e-8662-40dee116947c.png)
![image](https://user-images.githubusercontent.com/43174390/206371159-18d6f5c6-9e8b-4ec1-8df4-b8330e617ce6.png)

**Comment by WilsonXinxin** [comment] 2022-12-08 06:13
> 
it's svg file
![dir](https://user-images.githubusercontent.com/43174390/206371447-c18bfd72-a567-4b08-8e6c-618c3e38d83c.svg)

**Comment by vapensmianm149s** [comment] 2022-12-17 13:04
font-awesome-solid Not working, after restarting obsidian, it does not display properly

The probability of occurrence is low and there is no successful recurrence

**Comment by jpalm101** [comment] 2022-12-18 21:31
I am also seeing this issue. What is strange is that I have the plugin installed on my work computer, but when I sync all of my settings to my personal PC, all but one of my icons (probably have ~50) are grey. 

If it helps, the one that still has color icons is running 1.4.1. The computer that is has all of the grey icons is running the latest 1.4.3.

**Comment by FlorianWoelki** [comment] 2022-12-22 07:26
This is fixed in the [newest release](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.5.0). Thanks for reporting!

**Closed by FlorianWoelki** 2022-12-22 07:26 UTC
Labels: bug
