### ISSUE TITLE
Icon folder creation in vault

### ISSUE THREAD

**Issue by NB574** [FlorianWoelki/obsidian-icon-folder#80] opened 2022-06-17 04:43 UTC
Hi, whilst I read this is working as intended, is there a way to not have the icons download directly into my vault (and show within the file navigator), and to download into the plugin folder itself as they did before? 

Adding .obsidian prefix in the path pulls the icons into the folder used with previous versions (and I can see them in the expected folder in windows explorer), however as soon as I either try to delete (or move) the folder which shows in the file navigation itself in Obsidian, I am told to create an icon pack. Changing the default path is not sticking for me, it always defaults back to not having .obsidian as a prefix.

**Comment by FlorianWoelki** [comment] 2022-06-17 06:25
Thanks for reporting this issue. Unfortunately, I cannot reproduce the issue that the obsidian path is not saved correctly. The changes should still occur in the settings file of this plugin. 
Make sure to checkout version `1.2.3` if it is solved there.

**Comment by NB574** [comment] 2022-06-17 06:55
Oh thank you! That seems to have done the trick. Not sure why changing the path wouldn't stick for me, what you changed it to is the same as I had it. I tried on a fresh vault as well with nothing else installed and had the same issue, strange.

All icons reinstalled and working fine so far, the folder which was created in the file navingation has been moved into the folder I use for system bits and pieces, so it's out of the main navigation view. Restarting Obsidian no longer says I need an icon pack, and all icons are showing as they should.

Thanks again :)

**Comment by FlorianWoelki** [comment] 2022-06-17 07:16
> Oh thank you! That seems to have done the trick. Not sure why changing the path wouldn't stick for me, what you changed it to is the same as I had it. I tried on a fresh vault as well with nothing else installed and had the same issue, strange.
> 
> All icons reinstalled and working fine so far, the folder which was created in the file navingation has been moved into the folder I use for system bits and pieces, so it's out of the main navigation view. Restarting Obsidian no longer says I need an icon pack, and all icons are showing as they should.
> 
> Thanks again :)

Thanks for your feedback! I'll close this issue for now.

**Closed by FlorianWoelki** 2022-06-17 07:16 UTC
Labels: question
