### ISSUE TITLE
Icons keep disappearing

### ISSUE THREAD

**Issue by perigozin** [FlorianWoelki/obsidian-icon-folder#175] opened 2023-05-04 18:43 UTC
I updated to version 2.0 and had to reinstall the packs since a lot of  icons were missing, everytime I download a pack it comes with a different number of icons, everytime it comes with randomly missing icons and a few of them have completely different names, it's a nightmare. It's frustrating because I just had set almost 200 icons and now they are randomly missing, can't even find the ones I used before because they simply don't exist anymore. Also there is no longer the "fix" pack button next to each pack.

For example, the RiBookLine that I used previously is now missing and can't even be found in the icon selector anymore:

![image](https://user-images.githubusercontent.com/80776140/236296631-9bc704d3-4112-4a4c-9549-de54554a7405.png)

![image](https://user-images.githubusercontent.com/80776140/236297714-c8fa9d2f-a6d3-46d5-a0d5-9c22dd404544.png)

Everytime the "Total icons" number is different

![image](https://user-images.githubusercontent.com/80776140/236298309-25ceb611-2c12-4781-8d54-a1eb173815d5.png)

![image](https://user-images.githubusercontent.com/80776140/236298379-d997a2ae-7859-4846-b5c7-9f8a0c636c32.png)

![image](https://user-images.githubusercontent.com/80776140/236299752-3a823754-859b-4b41-87ae-d034a763e85e.png)

![image](https://user-images.githubusercontent.com/80776140/236298973-54fcfe6b-5631-4acf-9023-7aa0ce9a42ee.png)

People are having this kind of issues for a while now:

https://github.com/FlorianWoelki/obsidian-icon-folder/issues/90
https://github.com/FlorianWoelki/obsidian-icon-folder/issues/158
https://github.com/FlorianWoelki/obsidian-icon-folder/issues/163

**Comment by FlorianWoelki** [comment] 2023-05-04 21:14
I cannot reproduce this issue. It can be a problem with some syncing service again. I am keeping track of a possible solution for that at #153

**Comment by bololodev** [comment] 2023-05-04 21:58
I have no sync service or plugin, whenever I download a pack a few icons are not downloaded. It's an issue with this plugin. Unfortunately there are too many bugs and "I cannot reproduce this" to be reliable for real world usage. That's sad because it seemed to have potential, can't believe it's already in version 2.0.0, it should be 0.0.1 alpha maybe 🤷🏻‍♂️
Please warn the users in the README that they might spend all afternoon organizing their notes by icon and all that time may be in lost because the plugin misbehaves in all kinds of ways.

**Comment by FlorianWoelki** [comment] 2023-05-05 06:13
> I have no sync service or plugin, whenever I download a pack a few icons are not downloaded. It's an issue with this plugin. Unfortunately there are too many bugs and "I cannot reproduce this" to be reliable for real world usage. That's sad because it seemed to have potential, can't believe it's already in version 2.0.0, it should be 0.0.1 alpha maybe 🤷🏻‍♂️
> 
> Please warn the users in the README that they might spend all afternoon organizing their notes by icon and all that time may be in lost because the plugin misbehaves in all kinds of ways.

I am sorry to hear that. However I cannot really reproduce your described issue. It would be beneficial if you can provide me a minimal reproduction vault.
Everytime I try to download for example RemixIcons, I always have 2771 icons.

**Comment by liuke101** [comment] 2023-05-06 08:51
I had the same problem

**Comment by replete** [comment] 2023-05-06 10:54
I had this problem in earlier version when trying out new plugins. I theorized other plugins would somehow interact with the settings object and cause it to be corrupted.

**Comment by tomcatmew** [comment] 2023-05-07 09:14
update the plugin solved my problem

**Comment by theSmokingFrog** [comment] 2023-05-11 20:07
I was actually fighting with the exact same issue by @bololodev - overall I was not able to diagnose it correctly. At first I was under the impression that Obsidian Sync messed up something.

In a consistent way Remix Icons had 2271 after a fresh install, One restart later and the Icon Pack was missing 10 Icons. Even throwing a "Icon Not Found" Warning in the Developer Tools before the icon pack was even loaded. After trying everything that I could think of, I did the good old IT trick. I uninstalled it, restarted obsidian, installed it again and bam: works as intended.

Wild guess: Something went sideways in any of the config files during the upgrade from 1.7.0 to 2.0.0 - that's when the issues with the inconsistent Icon Pack behaviour started (before it was only missing icons due to obsidian Sync going haywire)

**Comment by jdillon** [comment] 2023-05-24 22:21
I am also seeing icons vanish :-\

**Comment by thegixo** [comment] 2023-05-26 12:18
@FlorianWoelki First of all, I wanted to thank you for your amazing plugin. I really enjoy using it. I'm having the icons disappearing issue recently. After I updated the plugin some of my icons got deleted but I don't have that issue now. My issue is that when I change some files or folders in my vault some icons disappear and by restarting the obsidian they reappear. This happens basically in any vault.

[IconTestVault.zip](https://github.com/FlorianWoelki/obsidian-icon-folder/files/11575085/IconTestVault.zip)
I attached a vault that I tried to reproduce the bug in it. There's a screen recording of its behavior, in the root of the vault.
I'm using Obsidian v1.3.4 on a Windows 11 machine.

Thank you again for your time and your work.

**Comment by bololodev** [comment] 2023-05-28 11:03
I wasn't able to solve this in my default vault. It always fails in some way when downloading new packs. There's probably some other plugin causing interference with icon-folder, since I have 20+ plugins installed and didn't have the time to test, I just created a new vault, installed all the icon packs, and copied the entire plugin folder to my original vault. Hasn't touched the configuration ever since because I'm afraid it might get messed up once again.

This kind of solved it, at least for me. Let's see in a future update of obsidian/icon-folder or if I decide to install an external pack if something happens then.

As for the other issue that was closed (#171) I'm not sure it was solved because that problem (icon names getting saved with dashes instead of their renamed version) happened ONLY when you freshly installed the plugin and DIDN'T restart Obsidian. The icons only get renamed after you restart Obsidian at least once, so any icons that may have been changed before restarting might have been saved with the wrong name, making them display the text instead of the actual icon once Obsidian restarts and actually renames the files. I could reproduce this even in a blank vault.

Lastly, maybe all these issues could be OS-related, which is why some are facing these problems while others are not. I'm using Windows, but I assume most here use macOS or Linux, so maybe it has to do with some specific Windows issue or the way it interfaces with the file system that may differ from other OSes.

**Comment by smileart** [comment] 2023-07-28 18:12
Have the same issue – seeing text instead of some icons. 

When I delete and install an icon set again, the icon appears, but some other icon from the same set down in the directory tree turns into text, etc. Wrote a script to check path existence for the used icons (based on data in `data.json`) and the picture is quite depressing – every single installation some icons are missing, which renders this plugin quite unusable (and that's with the Obsidian Sync turned entirely off. If we add Obsidian Sync, the lists of existing and inexisting icons are different on every device and every uninstall/install cycle in attempt to fix it produces hours of files being uploaded/downloaded/indexed/deleted/accepted/etc.):

```text
obsidian-icon-folder/icons/simple-icons/Go.svg✅                                                                                                                                   
obsidian-icon-folder/icons/simple-icons/Obsidian.svg✅                                                                                                                             
obsidian-icon-folder/icons/tabler-icons/Ufo.svg❌                                                                                                                                  
obsidian-icon-folder/icons/font-awesome-brands/Docker.svg❌                                                                                                                        
obsidian-icon-folder/icons/simple-icons/Openai.svg❌                                                                                                                               
obsidian-icon-folder/icons/font-awesome-solid/PersonDotsFromLine.svg❌                                                                                                             
obsidian-icon-folder/icons/remix-icons/UserSmileFill.svg✅                                                                                                                         
obsidian-icon-folder/icons/simple-icons/Rust.svg✅                                                                                                                                 
obsidian-icon-folder/icons/lucide-icons/Gamepad.svg❌                                                                                                                              
obsidian-icon-folder/icons/tabler-icons/WorldWww.svg❌                                                                                                                             
obsidian-icon-folder/icons/simple-icons/Neovim.svg✅                                                                                                                               
obsidian-icon-folder/icons/tabler-icons/Books.svg❌                                                                                                                                
obsidian-icon-folder/icons/lucide-icons/CalendarRange.svg❌                                                                                                                        
obsidian-icon-folder/icons/tabler-icons/TextSize.svg✅                                                                                                                             
obsidian-icon-folder/icons/lucide-icons/ToyBrick.svg❌                                                                                                                             
obsidian-icon-folder/icons/simple-icons/Wikipedia.svg❌                                                                                                                            
obsidian-icon-folder/icons/simple-icons/Ruby.svg✅                                                                                                                                 
obsidian-icon-folder/icons/font-awesome-solid/Guitar.svg✅                                                                                                                         
obsidian-icon-folder/icons/simple-icons/Bookstack.svg❌                                                                                                                            
obsidian-icon-folder/icons/font-awesome-solid/Passport.svg✅                                                                                                                       
obsidian-icon-folder/icons/font-awesome-solid/BookSkull.svg✅                                                                                                                      
obsidian-icon-folder/icons/tabler-icons/MapPinFilled.svg❌                                                                                                                         
obsidian-icon-folder/icons/font-awesome-brands/Readme.svg❌                                                                                                                        
obsidian-icon-folder/icons/font-awesome-brands/Chrome.svg❌                                                                                                                        
obsidian-icon-folder/icons/simple-icons/Apple.svg❌                                                                                                                                
obsidian-icon-folder/icons/lucide-icons/Camera.svg❌                                                                                                                               
obsidian-icon-folder/icons/font-awesome-solid/Cat.svg✅                                                                                                                            
obsidian-icon-folder/icons/lucide-icons/Cog.svg❌                                                                                                                                  
obsidian-icon-folder/icons/font-awesome-solid/BookAtlas.svg✅                                                                                                                      
obsidian-icon-folder/icons/icon-brew/DocumentCode.svg✅                                                                                                                            
obsidian-icon-folder/icons/tabler-icons/PingPong.svg❌                                                                                                                             
obsidian-icon-folder/icons/font-awesome-regular/Keyboard.svg✅                                                                                                                     
obsidian-icon-folder/icons/font-awesome-solid/Image.svg✅                                                                                                                          
obsidian-icon-folder/icons/font-awesome-solid/WhiskeyGlass.svg✅                                                                                                                   
obsidian-icon-folder/icons/lucide-icons/Paintbrush.svg❌                                                                                                                           
obsidian-icon-folder/icons/simple-icons/Openai.svg❌                                                                                                                               
obsidian-icon-folder/icons/lucide-icons/CalendarX.svg❌                                                                                                                            
obsidian-icon-folder/icons/font-awesome-solid/BoxOpen.svg✅                                                                                                                        
obsidian-icon-folder/icons/font-awesome-solid/Image.svg✅                                                                                                                          
obsidian-icon-folder/icons/font-awesome-solid/Brain.svg✅                                                                                                                          
obsidian-icon-folder/icons/tabler-icons/BadgeCc.svg❌                                                                                                                              
obsidian-icon-folder/icons/font-awesome-solid/BookMedical.svg✅                                                                                                                    
obsidian-icon-folder/icons/font-awesome-solid/BowlingBall.svg✅                                                                                                                    
obsidian-icon-folder/icons/tabler-icons/ChartDots.svg❌                                                                                                                            
obsidian-icon-folder/icons/tabler-icons/ManualGearbox.svg❌                                                                                                                        
obsidian-icon-folder/icons/remix-icons/MoneyPoundBoxFill.svg❌                                                                                                                     
obsidian-icon-folder/icons/simple-icons/Pwa.svg✅                                                                                                                                  
obsidian-icon-folder/icons/tabler-icons/Txt.svg✅                                                                                                                                  
obsidian-icon-folder/icons/simple-icons/F1.svg❌                                                                                                                                   
obsidian-icon-folder/icons/tabler-icons/Cpu.svg✅                                                                                                                                  
obsidian-icon-folder/icons/tabler-icons/Tower.svg❌                                                                                                                                
obsidian-icon-folder/icons/simple-icons/Gnubash.svg❌                                                                                                                              
obsidian-icon-folder/icons/remix-icons/FundsBoxFill.svg❌                                                                                                                          
obsidian-icon-folder/icons/remix-icons/PlantFill.svg❌                                                                                                                             
obsidian-icon-folder/icons/simple-icons/Javascript.svg✅                                                                                                                           
obsidian-icon-folder/icons/font-awesome-brands/Python.svg✅                                                                                                                        
obsidian-icon-folder/icons/simple-icons/Atom.svg❌                                                                                                                                 
obsidian-icon-folder/icons/simple-icons/Ffmpeg.svg❌                                                                                                                               
obsidian-icon-folder/icons/simple-icons/Git.svg❌
```

**Comment by netfly** [comment] 2023-08-27 13:58
Same here .... I use sync and I loose icons all the time on one device. When I remove and reactivate the icon pack again, then it works for a while, but I often have this issue. I really don't understand why.

**Comment by sobrinojulian** [comment] 2023-09-03 03:16
> maybe it has to do with some specific Windows issue
For me it works fine on Windows, but not at Linux or WSL

**Comment by FlorianWoelki** [comment] 2023-09-11 18:09
This issue has been resolved in the newest update.

**Closed by FlorianWoelki** 2023-09-11 18:09 UTC

**Comment by smileart** [comment] 2023-09-13 06:32
@FlorianWoelki I gave it another shot, installing the plug-in from scratch, installing all the packs, and setting `.obsidian/icons` as a path to avoid Sync issues (as per README recommendation). 

On the origin machine, all the icons seem to be all right. Repeating the process on another machine (apart from manually setting every icon) gives me a long list of notifications about the absence of the icons used, and icon text representations rendered next to each directory (while all packs are installed and choosing the same icon would stick alright). 

I'd expect if the icons are configured (and they clearly are because the text representations are there) and the packs are installed (and they are; otherwise I wouldn't be able to assign the same icons) then it would render the icons. Am I still doing something wrong? Is it a separate issue worth opening? 

Thank you for your time and effort. There's certainly some progress.

**Comment by FlorianWoelki** [comment] 2023-09-13 06:37
Thanks for the report. Do you think it is a syncing issue?

**Comment by smileart** [comment] 2023-09-13 08:31
@FlorianWoelki I don't see icons in `.obsidian/icons` being synced (in Sync logs) as they were in the plugin directory when I tried it before, so I guess it has nothing to do with syncing. It's weird that they don't appear cause as I said, they are clearly configured, cause all the text names next to the dirs match the expected/configured icons, and the icon packs are installed, cause I can choose any of them, but the replacement of the text  or rendering itself does not happen. I'll try to investigate later today. I'll let you know if I find something concrete. 🤝

**Comment by FlorianWoelki** [comment] 2023-09-13 08:33
> @FlorianWoelki I don't see icons in `.obsidian/icons` being synced (in Sync logs) as they were in the plugin directory when I tried it before, so I guess it has nothing to do with syncing. It's weird that they don't appear cause as I said, they are clearly configured, cause all the text names next to the dirs match the expected/configured icons, and the icon packs are installed, cause I can choose any of them, but the replacement of the text  or rendering itself does not happen. I'll try to investigate later today. I'll let you know if I find something concrete. 🤝 

Thank you! If possible you can also upload a minimal reproduction example, so that I can reproduce this.

**Comment by smileart** [comment] 2023-09-13 09:41
Ok, now I see! The thing is, when on machine 1️⃣ I configure icons they get extracted one by one, not all of them as it was before (which is **great**, it allows to keep them in plugin directory and not to struggle with thousands of icons being synchronised — I'll try it next). But, if you keep the icons in `.obsidian/icons` as recommended in README to avoid sync issues, when you get to machine 2️⃣ and install the plugin, `.obsidian/icons` contains only zipped packs and no used icons extracted into respective icon directories, hence the absence of them in the file tree.

**Example**:

Having a vault with two dirs/folders:

```
•
|_ AI
|_ Animals
```

- Imagine I configure `SiOpenai` Icon on machine 1️⃣ to be an icon for `AI` directory — it's set in `data.json`, rendered in the file tree next to AI – everything is great
- Then I go to machine 2️⃣ , the icon is not shown for `AI` directory (cause it was not configured on this machine, hence it's not extracted there — nothing to show)
- Next I configure `SiPuma` for `Animals` directory on machine 2️⃣ — again, everything is great, `data.json` now has two config records `"AI": "SiOpenai"` and `"Animals": "SiPuma"` and the icon `SiPuma` is rendered next to `Animals`, cause it was configured on this machine and therefore extracted there
- Now we have `SiOpenai` rendered on machine 1️⃣ but not on machine 2️⃣  and `SiPuma` rendered on machine 2️⃣  but not on machine 1️⃣  respectively

It sounds like the solution should be trivial: when used icons do not exist on current machine, but the icon pack is installed (the zip file is there) extract the used icons. I'm not sure ifObsidian plugin system has a post installation event or something, but that would be a good place to handle this – extract all the icons mentioned in `data.json` when the plugin got installed. The same could be added to "Icon Packs folder path" setting Save button, I guess.

Having said that, it sounds like the fix is still needed since you allow customising icons directory, setting it to one that is not being synced, but since the icons are extracted in much more effective way now (only used ones gonna be synced), I guess for me personally there's no reason anymore to keep them in `.obsidian/icons` I can switch back to default directory and sync a dozen of icons I use without need to wait for hour on end.

Sorry for a long-read :) Cheers!

**Comment by FlorianWoelki** [comment] 2023-09-13 09:58
> Ok, now I see! The thing is, when on machine 1️⃣ I configure icons they get extracted one by one, not all of them as it was before (which is **great**, it allows to keep them in plugin directory and not to struggle with thousands of icons being synchronised — I'll try it next). But, if you keep the icons in `.obsidian/icons` as recommended in README to avoid sync issues, when you get to machine 2️⃣ and install the plugin, `.obsidian/icons` contains only zipped packs and no used icons extracted into respective icon directories, hence the absence of them in the file tree.
> 
> **Example**:
> 
> Having a vault with two dirs/folders:
> 
> ```
> •
> |_ AI
> |_ Animals
> ```
> 
> * Imagine I configure `SiOpenai` Icon on machine 1️⃣ to be an icon for `AI` directory — it's set in `data.json`, rendered in the file tree next to AI – everything is great
> * Then I go to machine 2️⃣ , the icon is not shown for `AI` directory (cause it was not configured on this machine, hence it's not extracted there — nothing to show)
> * Next I configure `SiPuma` for `Animals` directory on machine 2️⃣ — again, everything is great, `data.json` now has two config records `"AI": "SiOpenai"` and `"Animals": "SiPuma"` and the icon `SiPuma` is rendered next to `Animals`, cause it was configured on this machine and therefore extracted there
> * Now we have `SiOpenai` rendered on machine 1️⃣ but not on machine 2️⃣  and `SiPuma` rendered on machine 2️⃣  but not on machine 1️⃣  respectively
> 
> It sounds like the solution should be trivial: when used icons do not exist on current machine, but the icon pack is installed (the zip file is there) extract the used icons. I'm not sure ifObsidian plugin system has a post installation event or something, but that would be a good place to handle this – extract all the icons mentioned in `data.json` when the plugin got installed. The same could be added to "Icon Packs folder path" setting Save button, I guess.
> 
> Having said that, it sounds like the fix is still needed since you allow customising icons directory, setting it to one that is not being synced, but since the icons are extracted in much more effective way now (only used ones gonna be synced), I guess for me personally there's no reason anymore to keep them in `.obsidian/icons` I can switch back to default directory and sync a dozen of icons I use without need to wait for hours on end.
> 
> Sorry for a long-read :) Cheers!

Thank you for the long description of the problem here!

But your syncing provider should also sync directory and files (svg's in this case) right? So the icon directories should be synced or am I wrong here. I don't quite understand yet, why the folders and icons do not exist on your second machine.

**Comment by smileart** [comment] 2023-09-13 10:31
That's a good question. I thought the whole point of using `.obsidian/icons` was that it goes with the app and is not synced. At least when I used this plugin before, and icons were kept in plugin's directory they were syncing in thousands, all the time, when I set `.obsidian/icons` they are not. My "provider" is Obsidian Sync, BTW.

Anyway, I tried to set `.obsidian/plugins/obsidian-icon-folder` as my path and the issue somehow persists, the icon I set on one machine is present there and in `data.json`, the `data.json` is updated on all devices, but the icons are not there, so they are not rendered. BTW, I have three devices in total: two Macs and one iPhone. So it is a synchronisation issue after all.

**Comment by FlorianWoelki** [comment] 2023-09-13 10:37
And it didn't log that it synced your zip files right?

**Comment by smileart** [comment] 2023-09-13 10:42
When I reinstall icon packs zip files get synced:

```
2023-09-13 13:39 - Server pushed [redacted] .obsidian/plugins/obsidian-icon-folder/simple-icons.zip
2023-09-13 13:39 - Downloading file .obsidian/plugins/obsidian-icon-folder/simple-icons.zip
2023-09-13 13:39 - Downloading complete .obsidian/plugins/obsidian-icon-folder/simple-icons.zip
2023-09-13 13:39 - Accepted .obsidian/plugins/obsidian-icon-folder/simple-icons.zip
2023-09-13 13:39 - Fully synced
```

**Comment by smileart** [comment] 2023-09-13 10:46
Let me do it in a clean way. I'll delete plugin on all machines. Install it again. Make sure the path is now in the plugin dir, not in `.obsidian/icons`, open all three logs and start setting icons in this way. I'll let you know if it works, but something tells me that is should.

**Comment by FlorianWoelki** [comment] 2023-09-13 12:16
> Let me do it in a clean way. I'll delete plugin on all machines. Install it again. Make sure the path is now in the plugin dir, not in `.obsidian/icons`, open all three logs and start setting icons in this way. I'll let you know if it works, but something tells me that is should.
> 
> **UPD**: I give up. I did exactly as I said ☝️ Deleted plugin on both laptops and the phone, installed it again, installed all packs on every machine, set an icon on one dir, while monitoring logs and seeing SVGs, ZIPs, and JSONs being fully synced on every step of the way. One laptop and the phone are in sync (at least after refreshing/reloading the app), the other laptop despite having all the packs and logging all the syncs – does not show/have the icon after all the syncs are finished.
> 
> I have rough understanding of why it's happening, but my lunch break is over and I don't have more time to investigate. What I noticed is that already installed packs/icons on installation/change on another machine get deleted and downloaded again (shown in the logs as "file was deleted or moved...") and since there's a three way sync, that might mess up the files on the third machine, deciding that is needs to be deleted or something.
> 
> **My suggestions would be**:
> 
> * cause the plugin is really popular and lots of people use Obsidian Sync and/or other ways of syncing, you need to try exactly that – take two computers and one phone (or any other count or combinations of those) and try to play around with some edge cases with logs monitoring on every step to figure out what goes wrong
> * figure out how to exclude icons/packs from synchronisation altogether, keep only the Folder ←→ Icon mapping data in JSON (BTW this one syncs with no issues whatsoever) and when the icon is configured in there, but absent on the disk — auto-install the pack / auto-extract the icon, that I believe would solve all the problems.
> 
> RN, though, it's still unusable for me. Sorry. 😔

Alright got it. Sorry for hearing this. I thought that the zip files would solve all the syncing issues.
So, a solution is basically trying to unzip the icons whenever they exist in the data. That's not an ideal solution because if you use a lot of icons, it will take some time.

Could you please create a new issue with your wonderful description and proposed solution? I would like to see if others have this issue as well.

**Comment by sobrinojulian** [comment] 2023-09-13 22:53
Just for the record, the 2 days ago update fixed the issue for me. In my case, it was unrelated to sync because I dont use it.

**Comment by serge-bedzhyk** [comment] 2023-10-13 09:38
Sorry I didn't create the issue, the thing is I found a folder icons solution that works perfectly for me and therefore I did not experiment with this plugin anymore.

**Comment by rivaldonovais** [comment] 2023-10-26 13:09
I was having the same problem. I discovered it was a **conflict** with the **MAKE.md** plugin.

**Comment by AlePaff** [comment] 2024-05-25 07:22
> I was having the same problem. I discovered it was a **conflict** with the **MAKE.md** plugin.

What kind of conflict?

**Comment by LaviStardust** [comment] 2024-07-08 22:22
Obsidian v1.6.5, Iconize 2.14.2, this issue still arises.
From one Obsidian restart to another, the number of icons in the pre-installed Lucide goes down, slowly breaking icons used through the vault, and removing them from the icon picker.

Is there a fix to this? Reinstalling does not fix this, and I would love to keep using this extension, it makes everything so much nicer.

**Comment by FlorianWoelki** [comment] 2024-07-09 06:45
> Obsidian v1.6.5, Iconize 2.14.2, this issue still arises. From one Obsidian restart to another, the number of icons in the pre-installed Lucide goes down, slowly breaking icons used through the vault, and removing them from the icon picker.
> 
> Is there a fix to this? Reinstalling does not fix this, and I would love to keep using this extension, it makes everything so much nicer.
> 
> Through restarting, I was able to take Lucide down from the expected 1479 to 1384. The `Icons background check` toggle does not affect this in any way I can notice.

Yes so this is "intended" because I wanted one icon pack which works well with Obsidian Sync. So it uses the natively used icons of Obsidian.
However, I am working on the ability to use the custom Lucide Icon pack again (#520). By now, you might want to use BRAT and freeze before the version 2.14.

**Comment by LaviStardust** [comment] 2024-07-09 12:40
So, the issue isn't necessarily with Iconize, but with the version of Lucide that Obsidian uses?
Today I noticed any freshly missing icon, also does not work for custom callouts.

Thank you for the BRAT suggestion, I will try this.
