### ISSUE TITLE
After most recent update, all icons gone

### ISSUE THREAD

**Issue by Psypher1** [FlorianWoelki/obsidian-icon-folder#189] opened 2023-06-01 13:41 UTC
After updating Icon folder all the folder icons are gone, the settings for the plugin as well as the right click menu for it

**Comment by FlorianWoelki** [comment] 2023-06-03 07:14
Please be more descriptive. What specific update version? Is there any error in the developer console of obsidian? Do you have a minimal reproducible example?

**Comment by carissas086** [comment] 2023-06-03 07:23
I've also had this problem. Updating to 1.3.5 today on Windows 10, and to 1.4.6 on iOS, the icons don't appear, and the plugin options in the right click context file explorer menu and in the settings all disappear.

**Comment by carissas086** [comment] 2023-06-03 07:28
The error showing on Obsidian in Windows 10 is:
![image](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/92591984/4a0048f1-fc62-4e67-bf88-d3a034cc4faa)

**Comment by Psypher1** [comment] 2023-06-03 11:14
Yeah, basically what @carissas086 has added is what I'm experiencing after updating

**Comment by aureusx** [comment] 2023-06-03 18:11
I debugged this a little, because it happened to me too. This might be helpful for the developer(s) as well as you users: This happens when you move files, as the filepath in the `data.json` can't be found in your vault anymore.

An easy fix for you now would be to fix the filepath(s) in that `data.json`: Just check all of them, they live in `<your obsidian config folder, usually .obsidian>/plugins/obsidian-icon-folder/data.json`. You will basically see a mapping from filepaths to icon names there, and I suppose that at least one of the filepaths will be wrong.

The other way to fix it would be to delete `data.json`, of course, but then you'd have to set everything up again.

**Comment by ameliette** [comment] 2023-06-04 10:49
I also have missing icons with the same TypeError, but i still have the plugin settings and context menu; icons disappear every time I close and reopen Obsidian. This started after updating to Icon Folder 2.0.2, and persists in 2.1.0 (Windows 11, Obsidian 1.3.5)

- context menu still has options to change and remove icon, even though no folder icon is visible
- re-installing Icon Folder does not fix this issue (as suggested in #175 for a similar, but different issue)

I am unable to recreate the disappearing icons bug in a fresh vault, but similar TypeErrors show up once Bookmarks core plugin is involved. 1 folder with 1 file, set icon to the folder, add the note into a bookmark group = Uncaught TypeError. The error does not happen when in Restricted Mode, and leaving Restricted Mode (re-enabling Icon Folder at the same time) also raises an error.

**Comment by FlorianWoelki** [comment] 2023-06-04 15:02
I wasn't really able to replicate this behavior. However, I've pushed a small fix and will release the version today. 

For now, I'll close the issue. If this issue still persists, please reopen it with a reproducible vault.

**Closed by FlorianWoelki** 2023-06-04 15:02 UTC
Labels: question

**Comment by carissas086** [comment] 2023-06-05 02:55
fix worked, error's gone from console and the settings have reappeared along w the icons. thank you!
